spring:
    profiles:
        active: default
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    datasource:
      url: ${timtask.delivery.datasource.url}
      driver-class-name: ${timtask.delivery.datasource.driver-class}
      username: ${timtask.delivery.datasource.username}
      password: ${timtask.delivery.datasource.password}
      type: ${timtask.delivery.datasource.type}
      druid:
        initial-size: ${timtask.delivery.datasource.initial-size}
        min-idle: ${timtask.delivery.datasource.min-idle}
        max-active: ${timtask.delivery.datasource.max-active}
        max-wait: ${timtask.delivery.datasource.max-wait}
        pool-prepared-statements: ${timtask.delivery.datasource.pool-prepared-statements}
        max-pool-prepared-statement-per-connection-size: ${timtask.delivery.datasource.max-pool-prepared-statement-per-connection-size}
        connection-properties: ${timtask.delivery.datasource.connection-properties}
       # filters: ${campaign.delivery.datasource.filters}
    rabbitmq:
        host: ${rabbitmq.host}
        port: ${rabbitmq.port}
        username: ${rabbitmq.username}
        password: ${rabbitmq.password}
        virtual-host: ${rabbitmq.virtual-host}

#    redis:
#        sentinel:
#            master: ${spring.redis.sentinel.master}
#            nodes: ${spring.redis.sentinel.nodes}
#        pool:
#            max-idle: ${spring.redis.pool.max-idle}
#            min-idle: ${spring.redis.pool.min-idle}
#            max-active: ${spring.redis.pool.max-active}
#            max-wait: ${spring.redis.pool.max-wait}
eureka:
    instance:
        prefer-ip-address: true
    client:
        healthcheck:
            enabled: true

server:
    tomcat:
        uri-encoding: UTF-8

mybatis:
    mapper-locations: mapper/*.xml

feign:
    hystrix:
        enabled: true
    compression:
        request:
            enable: true
        response:
            enable: true
    httpclient:
        enable: true

hystrix:
  command:
      coreSize: 60
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


