spring:
    profiles:
        active: default
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
#     datasource:
#       url: ${user.delivery.datasource.url}
#       driver-class-name: ${user.delivery.datasource.driver-class}
#       username: ${user.delivery.datasource.username}
#       password: ${user.delivery.datasource.password}
#       type: ${user.delivery.datasource.type}
#       druid:
#         initial-size: ${user.delivery.datasource.initial-size}
#         min-idle: ${user.delivery.datasource.min-idle}
#         max-active: ${user.delivery.datasource.max-active}
#         max-wait: ${user.delivery.datasource.max-wait}
#         pool-prepared-statements: ${user.delivery.datasource.pool-prepared-statements}
#         max-pool-prepared-statement-per-connection-size: ${user.delivery.datasource.max-pool-prepared-statement-per-connection-size}
#         connection-properties: ${user.delivery.datasource.connection-properties}
#        filters: ${common.delivery.datasource.filters}
    # rabbitmq:
    #     host: ${rabbitmq.host}
    #     port: ${rabbitmq.port}
    #     username: ${rabbitmq.username}
    #     password: ${rabbitmq.password}
    #     virtual-host: ${rabbitmq.virtual-host}

#     redis:
#         sentinel:
#             master: ${spring.redis.sentinel.master}
#             nodes: ${spring.redis.sentinel.nodes}
#         pool:
#             max-idle: ${spring.redis.pool.max-idle}
#             min-idle: ${spring.redis.pool.min-idle}
#             max-active: ${spring.redis.pool.max-active}
#             max-wait: ${spring.redis.pool.max-wait}
eureka:
    instance:
        prefer-ip-address: true
    client:
        healthcheck:
            enabled: true

server:
    tomcat:
        uri-encoding: UTF-8

# mybatis:
#     mapper-locations: mapper/*.xml

feign:
    hystrix:
        enabled: true
    compression:
        request:
            enable: true
        response:
            enable: true
    httpclient:
        enable: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


