spring:
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
eureka:
    instance:
        prefer-ip-address: true
    client:
        healthcheck:
            enabled: true

server:
    tomcat:
        uri-encoding: UTF-8

ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

zuul:
    ribbon:
        eager-load:
            enabled: true
    AuthorizationFilter:
        pre:
            disable: false
    routes:
        information-center:
            path: /information-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: information-center
        user-center:
            path: /user-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: user-center
        tenant-center:
            path: /tenant-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: tenant-center
        vehicle-refuel-center:
            path: /vehicle-refuel-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: vehicle-refuel-center
        timtask-center:
            path: /timtask-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: timtask-center
        campaign-center:
            path: /campaign-center/**
            stripPrefix: true
            sensitiveHeaders:
            serviceId: campaign-center







